POST http://localhost:5001/messages HTTP/1.1
Content-Type: application/json

{
  "text": "first!",
  "email": "qweer@asdf.co",
  "createdAt": "2020-10-10"
}
###
POST http://localhost:5001/messages HTTP/1.1
Content-Type: application/json

{
  "text": "???????????",
  "email": "anon@anon.net",
  "createdAt": "2020-10-10"
}
###
POST http://localhost:5001/messages HTTP/1.1
Content-Type: application/json

{
  "text": "first!!!!!!!!",
  "email": "qwer@qwer.qwer",
  "createdAt": "2020-10-10"
}

###
GET http://localhost:5001/messages HTTP/1.1

###
PUT http://localhost:5001/messages/99101614-702c-4116-bd35-a405bbae9552 HTTP/1.1
Content-Type: application/json

{
  "text": "???????????))))))",
  "email": "qwer@qwer.qwer",
  "createdAt": "2016-10-10"
}

###

DELETE http://localhost:5001/messages/99101614-702c-4116-bd35-a405bbae9552 HTTP/1.1