POST http://localhost:5001/messages
Content-Type: application/json

{
  "text": "first!",
  "email": "qweer@asdf.co",
  "createdAt": "2020-10-10"
}
###
POST http://localhost:5001/messages
Content-Type: application/json

{
  "text": "???????????",
  "email": "anon@anon.net",
  "createdAt": "2020-10-10"
}
###
POST http://localhost:5001/messages
Content-Type: application/json

{
  "text": "first!!!!!!!!",
  "email": "qwer@qwer.qwer",
  "createdAt": "2020-10-10"
}

###
GET http://localhost:5001/messages

###
PUT http://localhost:5001/messages/cd84cd8d-588e-4fa4-9c80-94677347d2b6
Content-Type: application/json

{
  "text": "???????????))))))",
  "email": "qwer@qwer.qwer",
  "createdAt": "2016-10-10"
}

###

DELETE http://localhost:5001/messages/cd84cd8d-588e-4fa4-9c80-94677347d2b6